global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']

