pipeline {
    agent any

    environment {
        IMAGE_NAME = "v${currentBuild.number}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/panasyg/jenkins-cicd-monitoring.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME} ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker-compose up -d"
                }
            }
        }

        stage('Test Application') {
            steps {
                script {
                    sh """
                    sleep 5 
                    curl --fail http://localhost:5000/health || exit 1
                    """
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    sh "docker-compose down"
                }
            }
        }
    }

    post {
        always {
            sh "docker ps -a"
        }
        success {
            echo "Successfull pipeline execution"
        }
        failure {
            echo "Pipeline has failed"
        }
    }
}

